c=======================================================================
c  CoheleBulkMap.f  -- standalone shim (intentionally empty)
c
c  umat.for does `include 'UEL.for'`, and UEL.for (the cohesive-element
c  user element, unused by the C3D8 crystal-plasticity replay) does
c  `include 'CoheleBulkMap.f'` inside its body.  In a real DiscreteTwin
c  job that file is a per-mesh table generated by CoheleBulkMap.py, e.g.
c        cohelebulkmap(1,:) = (/1,1,1/)
c        ...
c  The HCPnoTwin example ships NO CoheleBulkMap.f (no cohesive elements),
c  so this empty stub lets UEL.for's `include` resolve when the whole
c  umat.for translation unit is compiled.  UEL is never CALLED by the
c  material-point driver, so leaving cohelebulkmap uninitialised is fine.
c
c  Place this directory FIRST on the include path so this stub is found
c  ahead of any real per-mesh table.
c=======================================================================
