"""Nonlinear-spring sensitivity — first real R^(1) generation (vertical slice).

Proves the framework can *produce* R^(1) from a hypercomplex (dual-number)
residual evaluation and solve  T U^(1) = -R^(1)  correctly, matching the
closed-form derivative and finite differences. R^(1) is generated by the backend
+ provider (generate_rhs=True), NOT by manually calling set_residual_order.

Toy: R = k u^3 - f  ->  u=(f/k)^(1/3), T=3ku^2, dR/dk=u^3, du/dk=-u/(3k).

Run: python tests/framework/test_nonlinear_spring_sensitivity.py
"""

import json
import os
import sys
import tempfile

import numpy as np
import pytest

_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir, os.pardir))
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

from residual_core import ResidualProblem
from residual_core.core.model import Model, Element
from residual_core.materials.base import MaterialBinding
from residual_core.algebra.dual1 import Dual1, seed, imag_part, real_part

K, F = 2.0, 16.0
U_EXACT = (F / K) ** (1.0 / 3.0)              # = 2.0
DUDK_EXACT = -U_EXACT / (3.0 * K)            # = -1/3


def _script_run(fn, *args):
    """Script-mode runner: a test passes unless it raises AssertionError."""
    try:
        fn(*args)
    except AssertionError as exc:
        print("  FAIL: %s" % exc)
        return False
    except pytest.skip.Exception as exc:
        print("  SKIP: %s" % exc)
    return True


def _report(checks):
    """Print every check, then assert that none failed (same condition as all())."""
    for label, v in checks:
        print("  %-38s -> %s" % (label, "PASS" if v else "FAIL"))
    failed = [label for label, v in checks if not v]
    assert not failed, "failed checks: " + "; ".join(failed)


def _spring_problem():
    m = Model(nodes={1: (0.0, 0.0, 0.0)})
    m.elements[1] = Element(1, "SPRING1", [1])
    m.element_material = {1: "spring"}
    b = MaterialBinding(material=None, name="spring")
    b.section = {"k": K, "f": F}
    m.materials = {"spring": b}
    return ResidualProblem(m)


def test_dual1_algebra():
    x = seed(3.0)                            # 3 + eps
    # d/dx (x^3) = 3x^2 = 27 ; (x^3 - 5)*2 -> imag 2*27=54
    r = (x ** 3 - 5.0) * 2.0
    checks = [
        ("real part", abs(real_part(r) - (3.0 ** 3 - 5.0) * 2.0) < 1e-12),
        ("imag = derivative", abs(imag_part(r) - 54.0) < 1e-12),
        ("division derivative", abs(imag_part(seed(4.0) / 2.0) - 0.5) < 1e-12),
        ("float commutes", abs(imag_part(2.0 * seed(1.0)) - 2.0) < 1e-12),
    ]
    _report(checks)


def test_real_solution_and_tangent():
    p = _spring_problem()
    u = p.solve_newton("formulation")
    res = p.result("formulation", U=u)
    checks = [
        ("u matches (f/k)^(1/3)", abs(u[0] - U_EXACT) < 1e-10),
        ("R ~ 0 at solution", res.free_residual_norm < 1e-9),
        ("tangent = 3 k u^2",
         abs(float(res.tangent.T[0, 0]) - 3 * K * u[0] ** 2) < 1e-9),
        ("tangent source backend-assembled",
         res.tangent.source == "backend-assembled"),
    ]
    _report(checks)


def test_rhs_generated_and_solved():
    p = _spring_problem()
    # generate_rhs=True: the backend+provider PRODUCE R^(1) (no manual set here).
    # backend="dual1" is the legacy first-order smoke test (default is otilib).
    pkg = p.sensitivity_package(mode="formulation", parameters=["spring.k"],
                                generate_rhs=True, fd_check=True, backend="dual1")
    u = pkg.residual.diagnostics  # noqa (touch)
    R1 = pkg.sensitivity.R(1)
    checks = [
        ("R^(1) generated (not None)", R1 is not None),
        ("hypercomplex ready",
         pkg.sensitivity.diagnostics.get("hypercomplex_ready") is True),
        ("R^(1) = dR/dk = u^3", abs(float(R1[0, 0]) - U_EXACT ** 3) < 1e-9),
        ("rhs^(1) = -R^(1)",
         np.allclose(pkg.sensitivity.rhs(1), -R1)),
        ("system ready", pkg.system_ready(1)),
    ]
    U1 = pkg.solve(1)
    dudk = float(U1[0, 0])
    checks += [
        ("du/dk = -u/(3k)", abs(dudk - DUDK_EXACT) < 1e-9),
        ("validation overall pass", pkg.validation.overall_passed is True),
    ]
    # a finite-difference check is present and passed
    fd_checks = [c for c in pkg.validation.checks
                 if c.name == "sensitivity-vs-finite-difference"]
    checks.append(("FD cross-check present + passed",
                   bool(fd_checks) and fd_checks[0].passed))
    _report(checks)


def test_independent_finite_difference():
    p = _spring_problem()
    p.solve_newton("formulation")
    pkg = p.sensitivity_package(mode="formulation", parameters=["spring.k"],
                                generate_rhs=True, fd_check=False, backend="dual1")
    U1 = pkg.solve(1)[0, 0]
    fd = p.finite_difference_sensitivity("formulation", ["spring.k"])[0, 0]
    ok = abs(U1 - fd) / abs(fd) < 1e-4 and abs(fd - DUDK_EXACT) < 1e-4
    print("  %-38s -> %s" % ("solved vs independent FD vs analytic",
                             "PASS" if ok else "FAIL"))
    assert ok, ("solved du/dk=%.9g vs FD=%.9g vs analytic=%.9g "
                "(need rel(U1,FD) < 1e-4 and |FD-analytic| < 1e-4)"
                % (U1, fd, DUDK_EXACT))


def test_serialization():
    p = _spring_problem()
    pkg = p.sensitivity_package(mode="formulation", parameters=["spring.k"],
                                generate_rhs=True, backend="dual1")
    d = tempfile.mkdtemp()
    pkg.save(os.path.join(d, "spring"))
    files = set(os.listdir(d))
    with open(os.path.join(d, "spring.json"), encoding="utf-8") as fh:
        meta = json.load(fh)
    npz = np.load(os.path.join(d, "spring.npz"), allow_pickle=True)
    checks = [
        ("json/npz/md written",
         {"spring.json", "spring.npz", "spring.md"} <= files),
        ("sub-results written",
         {"spring_sensitivity.json", "spring_residual.npz"} <= files),
        ("target system recorded", meta["target_system"] == "T U^(p) = -R^(p)"),
        ("R^(1) array in npz", "sensitivity_R_order_1" in npz),
        ("rhs^(1) array in npz", "sensitivity_rhs_order_1" in npz),
        ("R^(1) value = u^3",
         abs(float(npz["sensitivity_R_order_1"][0, 0]) - U_EXACT ** 3) < 1e-9),
    ]
    _report(checks)


def test_example_loads():
    ex = os.path.join(_ROOT, "residual_core", "examples",
                      "minimal_nonlinear_spring_sensitivity", "model.json")
    p = ResidualProblem.from_neutral(ex)
    pkg = p.sensitivity_package(mode="formulation", parameters=["spring.k"],
                                generate_rhs=True, backend="dual1")
    ready = pkg.system_ready(1)
    dudk = float(pkg.solve(1)[0, 0]) if ready else float("nan")
    ok = ready and abs(dudk - DUDK_EXACT) < 1e-9
    print("  %-38s -> %s" % ("neutral example solves du/dk", "PASS" if ok else "FAIL"))
    assert ok, ("neutral example: system_ready=%r du/dk=%.9g (need %.9g, tol 1e-9)"
                % (ready, dudk, DUDK_EXACT))


def main():
    print("Nonlinear-spring sensitivity (first real R^(1) generation)")
    results = [_script_run(fn) for fn in (
        test_dual1_algebra,
        test_real_solution_and_tangent,
        test_rhs_generated_and_solved,
        test_independent_finite_difference,
        test_serialization,
        test_example_loads,
    )]
    ok = all(results)
    print("OVERALL: %s" % ("ALL PASS" if ok else "FAILURE"))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
